############################
# Includes
############################

include theme.conf
include splits.conf

############################
# Fonte
############################

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13

disable_ligatures never

############################
# Cursor
############################

cursor_shape block
cursor_blink_interval 0.5

############################
# Scrollback
############################

scrollback_lines 1000000

############################
# Aparência
############################

background_opacity 0.94

window_padding_width 8

confirm_os_window_close 0

enable_audio_bell no

visual_bell_duration 0

remember_window_size yes

############################
# Clipboard
############################

copy_on_select yes

strip_trailing_spaces smart

############################
# Mouse
############################

hide_window_decorations no

############################
# Performance
############################

repaint_delay 10

input_delay 3

sync_to_monitor yes

############################
# Shell
############################

shell zsh

############################
# URLs
############################

detect_urls yes
