# Split vertical (lado a lado)
map ctrl+s launch --location=vsplit

# Split horizontal
map ctrl+d launch --location=hsplit

# Fecha janela atual
map ctrl+w close_window

# Próximo painel
map ctrl+l next_window

# Painel anterior
map ctrl+h previous_window

# Nova aba
map ctrl+t new_tab

# Fecha aba
map ctrl+shift+w close_tab

# Próxima aba
map ctrl+tab next_tab

# Aba anterior
map ctrl+shift+tab previous_tab
